#!/usr/bin/env bash
# Tell the story of passwd
file="/etc/passwd"
while IFS=: read -r username password uid gid full_name home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $full_name"
done < "$file"
